#! /usr/bin/env bash

tt ./lib/cskit/parsers/science_health/science_health.treetop
bundle exec ruby -e "require 'pry'; require 'pry-nav'; require 'cskit'; p = CSKit::Parsers::ScienceHealthParser.new; binding.pry"
